// <auto-generated />
using System;
using AspNetCoreDemoApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCoreDemoApp.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190223162841_Institute_set_Name_required")]
    partial class Institute_set_Name_required
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Institute", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Institute");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Mentor", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("FK_Institute");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("Photo")
                        .HasMaxLength(100);

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("FK_Institute");

                    b.ToTable("Mentor");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.MentorRequest", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<long>("FK_Mentor");

                    b.Property<long>("FK_Project");

                    b.Property<int>("State");

                    b.HasKey("ID");

                    b.HasIndex("FK_Mentor");

                    b.HasIndex("FK_Project");

                    b.ToTable("MentorRequest");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Partner", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Website")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("Partner");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Project", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("Duration");

                    b.Property<long?>("FK_Mentor");

                    b.Property<long>("FK_Partner");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ProjectCategory")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("FK_Mentor");

                    b.HasIndex("FK_Partner");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Student", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("FK_Institute");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<string>("Photo")
                        .HasMaxLength(100);

                    b.Property<int>("Semester");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(350);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.HasIndex("FK_Institute");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Student2Project", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("FK_Project");

                    b.Property<long>("FK_Student");

                    b.HasKey("ID");

                    b.HasIndex("FK_Project");

                    b.HasIndex("FK_Student");

                    b.ToTable("Student2Project");
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Mentor", b =>
                {
                    b.HasOne("AspNetCoreDemoApp.Model.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("FK_Institute")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.MentorRequest", b =>
                {
                    b.HasOne("AspNetCoreDemoApp.Model.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("FK_Mentor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreDemoApp.Model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("FK_Project")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Project", b =>
                {
                    b.HasOne("AspNetCoreDemoApp.Model.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("FK_Mentor");

                    b.HasOne("AspNetCoreDemoApp.Model.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("FK_Partner")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Student", b =>
                {
                    b.HasOne("AspNetCoreDemoApp.Model.Institute", "Institute")
                        .WithMany()
                        .HasForeignKey("FK_Institute")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspNetCoreDemoApp.Model.Student2Project", b =>
                {
                    b.HasOne("AspNetCoreDemoApp.Model.Project", "Project")
                        .WithMany()
                        .HasForeignKey("FK_Project")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreDemoApp.Model.Student", "Student")
                        .WithMany()
                        .HasForeignKey("FK_Student")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
